import type { LetterPickOption, Puzzle } from "./puzzleTypes";

export type LetterPickEntry = {
  /** Puzzle letter key a–z. */
  key: string;
  /** Display form for speech (usually noun capitalization). */
  display: string;
  /** Filename slug under letterpick/<key>/. */
  slug: string;
  /** Public path without leading slash, e.g. art/letterpick/a/affe.png */
  artPath: string;
};

export type { LetterPickOption };

/** NFC + de-DE lower; ä/ö/ü/ß stay distinct (ä≠a, ß≠s). */
export function wordContainsLetter(word: string, letter: string): boolean {
  const key = letter.normalize("NFC").toLocaleLowerCase("de-DE");
  if (!/^[a-z]$/.test(key)) return false;
  const chars = [...word.normalize("NFC").toLocaleLowerCase("de-DE")];
  return chars.includes(key);
}

function entry(key: string, display: string, slug: string): LetterPickEntry {
  return { key, display, slug, artPath: `art/letterpick/${key}/${slug}.png` };
}

/** 26 × 30 = 780 grade-1-ish examples; same stem under two keys = two art paths. */
export const LETTER_PICK_ITEMS: readonly LetterPickEntry[] = [
  entry('a', 'Affe', 'affe'),
  entry('a', 'Apfel', 'apfel'),
  entry('a', 'Auto', 'auto'),
  entry('a', 'Ameise', 'ameise'),
  entry('a', 'Ananas', 'ananas'),
  entry('a', 'Adler', 'adler'),
  entry('a', 'Auge', 'auge'),
  entry('a', 'Arm', 'arm'),
  entry('a', 'Ball', 'ball'),
  entry('a', 'Katze', 'katze'),
  entry('a', 'Mama', 'mama'),
  entry('a', 'Papa', 'papa'),
  entry('a', 'Nase', 'nase'),
  entry('a', 'Hase', 'hase'),
  entry('a', 'Tasche', 'tasche'),
  entry('a', 'Garten', 'garten'),
  entry('a', 'Laterne', 'laterne'),
  entry('a', 'Banane', 'banane'),
  entry('a', 'Kamera', 'kamera'),
  entry('a', 'Panda', 'panda'),
  entry('a', 'Lama', 'lama'),
  entry('a', 'Salat', 'salat'),
  entry('a', 'Pasta', 'pasta'),
  entry('a', 'Kaktus', 'kaktus'),
  entry('a', 'Mantel', 'mantel'),
  entry('a', 'Wasser', 'wasser'),
  entry('a', 'Tasse', 'tasse'),
  entry('a', 'Lampe', 'lampe'),
  entry('a', 'Radar', 'radar'),
  entry('a', 'Lava', 'lava'),
  entry('b', 'Ball', 'ball'),
  entry('b', 'Baum', 'baum'),
  entry('b', 'Buch', 'buch'),
  entry('b', 'Biene', 'biene'),
  entry('b', 'Brot', 'brot'),
  entry('b', 'Banane', 'banane'),
  entry('b', 'Birne', 'birne'),
  entry('b', 'Boot', 'boot'),
  entry('b', 'Bus', 'bus'),
  entry('b', 'Bär', 'baer'),
  entry('b', 'Baby', 'baby'),
  entry('b', 'Berg', 'berg'),
  entry('b', 'Blume', 'blume'),
  entry('b', 'Besen', 'besen'),
  entry('b', 'Becher', 'becher'),
  entry('b', 'Biber', 'biber'),
  entry('b', 'Boden', 'boden'),
  entry('b', 'Band', 'band'),
  entry('b', 'Bahn', 'bahn'),
  entry('b', 'Bild', 'bild'),
  entry('b', 'Brief', 'brief'),
  entry('b', 'Brille', 'brille'),
  entry('b', 'Brett', 'brett'),
  entry('b', 'Bude', 'bude'),
  entry('b', 'Bohne', 'bohne'),
  entry('b', 'Bagger', 'bagger'),
  entry('b', 'Becken', 'becken'),
  entry('b', 'Bolzen', 'bolzen'),
  entry('b', 'Bub', 'bub'),
  entry('b', 'Bube', 'bube'),
  entry('c', 'Computer', 'computer'),
  entry('c', 'Clown', 'clown'),
  entry('c', 'Comic', 'comic'),
  entry('c', 'Cello', 'cello'),
  entry('c', 'Cafe', 'cafe'),
  entry('c', 'Camping', 'camping'),
  entry('c', 'Couch', 'couch'),
  entry('c', 'Creme', 'creme'),
  entry('c', 'Croissant', 'croissant'),
  entry('c', 'Cupcake', 'cupcake'),
  entry('c', 'Curry', 'curry'),
  entry('c', 'Circus', 'circus'),
  entry('c', 'Coach', 'coach'),
  entry('c', 'Code', 'code'),
  entry('c', 'Cargo', 'cargo'),
  entry('c', 'Center', 'center'),
  entry('c', 'Chili', 'chili'),
  entry('c', 'Chips', 'chips'),
  entry('c', 'Citrone', 'citrone'),
  entry('c', 'Clip', 'clip'),
  entry('c', 'Club', 'club'),
  entry('c', 'Cactus', 'cactus'),
  entry('c', 'Candle', 'candle'),
  entry('c', 'Canyon', 'canyon'),
  entry('c', 'Cassette', 'cassette'),
  entry('c', 'Cement', 'cement'),
  entry('c', 'Ceramic', 'ceramic'),
  entry('c', 'Cereal', 'cereal'),
  entry('c', 'Charm', 'charm'),
  entry('c', 'Cheese', 'cheese'),
  entry('d', 'Dose', 'dose'),
  entry('d', 'Dach', 'dach'),
  entry('d', 'Hund', 'hund'),
  entry('d', 'Rad', 'rad'),
  entry('d', 'Adler', 'adler'),
  entry('d', 'Nadel', 'nadel'),
  entry('d', 'Laden', 'laden'),
  entry('d', 'Kinder', 'kinder'),
  entry('d', 'Mond', 'mond'),
  entry('d', 'Wind', 'wind'),
  entry('d', 'Hand', 'hand'),
  entry('d', 'Sand', 'sand'),
  entry('d', 'Mund', 'mund'),
  entry('d', 'Wald', 'wald'),
  entry('d', 'Feld', 'feld'),
  entry('d', 'Bild', 'bild'),
  entry('d', 'Band', 'band'),
  entry('d', 'Bad', 'bad'),
  entry('d', 'Dorf', 'dorf'),
  entry('d', 'Drache', 'drache'),
  entry('d', 'Delfin', 'delfin'),
  entry('d', 'Decke', 'decke'),
  entry('d', 'Daumen', 'daumen'),
  entry('d', 'Donner', 'donner'),
  entry('d', 'Dusche', 'dusche'),
  entry('d', 'Dolch', 'dolch'),
  entry('d', 'Dachs', 'dachs'),
  entry('d', 'Dom', 'dom'),
  entry('d', 'Diesel', 'diesel'),
  entry('d', 'Panda', 'panda'),
  entry('e', 'Esel', 'esel'),
  entry('e', 'Ente', 'ente'),
  entry('e', 'Eule', 'eule'),
  entry('e', 'Erde', 'erde'),
  entry('e', 'Essen', 'essen'),
  entry('e', 'Eimer', 'eimer'),
  entry('e', 'Engel', 'engel'),
  entry('e', 'Eiche', 'eiche'),
  entry('e', 'Edelstein', 'edelstein'),
  entry('e', 'Elch', 'elch'),
  entry('e', 'Elefant', 'elefant'),
  entry('e', 'Beere', 'beere'),
  entry('e', 'Nase', 'nase'),
  entry('e', 'Hase', 'hase'),
  entry('e', 'Rose', 'rose'),
  entry('e', 'See', 'see'),
  entry('e', 'Meer', 'meer'),
  entry('e', 'Apfel', 'apfel'),
  entry('e', 'Banane', 'banane'),
  entry('e', 'Laterne', 'laterne'),
  entry('e', 'Kerze', 'kerze'),
  entry('e', 'Feder', 'feder'),
  entry('e', 'Regen', 'regen'),
  entry('e', 'Schnee', 'schnee'),
  entry('e', 'Sterne', 'sterne'),
  entry('e', 'Fenster', 'fenster'),
  entry('e', 'Teller', 'teller'),
  entry('e', 'Messer', 'messer'),
  entry('e', 'Becher', 'becher'),
  entry('e', 'Lehrer', 'lehrer'),
  entry('f', 'Fisch', 'fisch'),
  entry('f', 'Fuchs', 'fuchs'),
  entry('f', 'Frosch', 'frosch'),
  entry('f', 'Feuer', 'feuer'),
  entry('f', 'Feder', 'feder'),
  entry('f', 'Fahne', 'fahne'),
  entry('f', 'Fahrrad', 'fahrrad'),
  entry('f', 'Fenster', 'fenster'),
  entry('f', 'Flasche', 'flasche'),
  entry('f', 'Fliege', 'fliege'),
  entry('f', 'Schiff', 'schiff'),
  entry('f', 'Affe', 'affe'),
  entry('f', 'Hof', 'hof'),
  entry('f', 'Dorf', 'dorf'),
  entry('f', 'Wolf', 'wolf'),
  entry('f', 'Schaf', 'schaf'),
  entry('f', 'Brief', 'brief'),
  entry('f', 'Kartoffel', 'kartoffel'),
  entry('f', 'Giraffe', 'giraffe'),
  entry('f', 'Telefon', 'telefon'),
  entry('f', 'Koffer', 'koffer'),
  entry('f', 'Löffel', 'loeffel'),
  entry('f', 'Waffe', 'waffe'),
  entry('f', 'Seife', 'seife'),
  entry('f', 'Pfeffer', 'pfeffer'),
  entry('f', 'Kaffee', 'kaffee'),
  entry('f', 'Fohlen', 'fohlen'),
  entry('f', 'Felsen', 'felsen'),
  entry('f', 'Falke', 'falke'),
  entry('f', 'Fluss', 'fluss'),
  entry('g', 'Gabel', 'gabel'),
  entry('g', 'Garten', 'garten'),
  entry('g', 'Gans', 'gans'),
  entry('g', 'Geige', 'geige'),
  entry('g', 'Geld', 'geld'),
  entry('g', 'Geschenk', 'geschenk'),
  entry('g', 'Glas', 'glas'),
  entry('g', 'Glocke', 'glocke'),
  entry('g', 'Gras', 'gras'),
  entry('g', 'Gurke', 'gurke'),
  entry('g', 'Vogel', 'vogel'),
  entry('g', 'Auge', 'auge'),
  entry('g', 'Regen', 'regen'),
  entry('g', 'Wagen', 'wagen'),
  entry('g', 'Bogen', 'bogen'),
  entry('g', 'Nagel', 'nagel'),
  entry('g', 'Ziegel', 'ziegel'),
  entry('g', 'Tiger', 'tiger'),
  entry('g', 'Ziege', 'ziege'),
  entry('g', 'Berg', 'berg'),
  entry('g', 'Weg', 'weg'),
  entry('g', 'Tag', 'tag'),
  entry('g', 'Zug', 'zug'),
  entry('g', 'Flug', 'flug'),
  entry('g', 'Ring', 'ring'),
  entry('g', 'Ding', 'ding'),
  entry('g', 'Spiegel', 'spiegel'),
  entry('g', 'Igel', 'igel'),
  entry('g', 'Angel', 'angel'),
  entry('g', 'Sagen', 'sagen'),
  entry('h', 'Hund', 'hund'),
  entry('h', 'Hase', 'hase'),
  entry('h', 'Haus', 'haus'),
  entry('h', 'Hand', 'hand'),
  entry('h', 'Hut', 'hut'),
  entry('h', 'Herz', 'herz'),
  entry('h', 'Hose', 'hose'),
  entry('h', 'Hahn', 'hahn'),
  entry('h', 'Huhn', 'huhn'),
  entry('h', 'Himmel', 'himmel'),
  entry('h', 'Buch', 'buch'),
  entry('h', 'Nacht', 'nacht'),
  entry('h', 'Licht', 'licht'),
  entry('h', 'Milch', 'milch'),
  entry('h', 'Schuh', 'schuh'),
  entry('h', 'Schaf', 'schaf'),
  entry('h', 'Hirsch', 'hirsch'),
  entry('h', 'Kirche', 'kirche'),
  entry('h', 'Kuh', 'kuh'),
  entry('h', 'Ohr', 'ohr'),
  entry('h', 'Zahn', 'zahn'),
  entry('h', 'Lehrer', 'lehrer'),
  entry('h', 'Schule', 'schule'),
  entry('h', 'Reh', 'reh'),
  entry('h', 'Fuchs', 'fuchs'),
  entry('h', 'Frosch', 'frosch'),
  entry('h', 'Schiff', 'schiff'),
  entry('h', 'Fahrrad', 'fahrrad'),
  entry('h', 'Hochzeit', 'hochzeit'),
  entry('h', 'Hirschkalb', 'hirschkalb'),
  entry('i', 'Igel', 'igel'),
  entry('i', 'Insel', 'insel'),
  entry('i', 'Ibis', 'ibis'),
  entry('i', 'Idee', 'idee'),
  entry('i', 'Iris', 'iris'),
  entry('i', 'Kino', 'kino'),
  entry('i', 'Biene', 'biene'),
  entry('i', 'Linie', 'linie'),
  entry('i', 'Mini', 'mini'),
  entry('i', 'Taxi', 'taxi'),
  entry('i', 'Pizza', 'pizza'),
  entry('i', 'Tiger', 'tiger'),
  entry('i', 'Bild', 'bild'),
  entry('i', 'Fisch', 'fisch'),
  entry('i', 'Milch', 'milch'),
  entry('i', 'Licht', 'licht'),
  entry('i', 'Kirsche', 'kirsche'),
  entry('i', 'Pinie', 'pinie'),
  entry('i', 'Krokodil', 'krokodil'),
  entry('i', 'Indien', 'indien'),
  entry('i', 'Insekt', 'insekt'),
  entry('i', 'Instrument', 'instrument'),
  entry('i', 'Igelhaus', 'igelhaus'),
  entry('i', 'Iglu', 'iglu'),
  entry('i', 'Irisblatt', 'irisblatt'),
  entry('i', 'Miniatur', 'miniatur'),
  entry('i', 'Bikini', 'bikini'),
  entry('i', 'Ciabatta', 'ciabatta'),
  entry('i', 'Chili', 'chili'),
  entry('i', 'Zitrone', 'zitrone'),
  entry('j', 'Jacke', 'jacke'),
  entry('j', 'Joker', 'joker'),
  entry('j', 'Joghurt', 'joghurt'),
  entry('j', 'Journal', 'journal'),
  entry('j', 'Jazz', 'jazz'),
  entry('j', 'Jeep', 'jeep'),
  entry('j', 'Job', 'job'),
  entry('j', 'Juice', 'juice'),
  entry('j', 'Jungle', 'jungle'),
  entry('j', 'Junior', 'junior'),
  entry('j', 'Junge', 'junge'),
  entry('j', 'Jäger', 'jaeger'),
  entry('j', 'Jagd', 'jagd'),
  entry('j', 'Jahr', 'jahr'),
  entry('j', 'Januar', 'januar'),
  entry('j', 'Japan', 'japan'),
  entry('j', 'Jeans', 'jeans'),
  entry('j', 'Jet', 'jet'),
  entry('j', 'Jubel', 'jubel'),
  entry('j', 'Jugend', 'jugend'),
  entry('j', 'Juli', 'juli'),
  entry('j', 'Juni', 'juni'),
  entry('j', 'Jurist', 'jurist'),
  entry('j', 'Juwel', 'juwel'),
  entry('j', 'Jacht', 'jacht'),
  entry('j', 'Jade', 'jade'),
  entry('j', 'Jaguar', 'jaguar'),
  entry('j', 'Jam', 'jam'),
  entry('j', 'Jasmin', 'jasmin'),
  entry('j', 'Jogger', 'jogger'),
  entry('k', 'Katze', 'katze'),
  entry('k', 'Kuh', 'kuh'),
  entry('k', 'Kuchen', 'kuchen'),
  entry('k', 'Krokodil', 'krokodil'),
  entry('k', 'Kamera', 'kamera'),
  entry('k', 'Kaktus', 'kaktus'),
  entry('k', 'Kerze', 'kerze'),
  entry('k', 'Kind', 'kind'),
  entry('k', 'Kissen', 'kissen'),
  entry('k', 'Koch', 'koch'),
  entry('k', 'Rock', 'rock'),
  entry('k', 'Socke', 'socke'),
  entry('k', 'Jacke', 'jacke'),
  entry('k', 'Paket', 'paket'),
  entry('k', 'Rakete', 'rakete'),
  entry('k', 'Laken', 'laken'),
  entry('k', 'Haken', 'haken'),
  entry('k', 'Ecke', 'ecke'),
  entry('k', 'Decke', 'decke'),
  entry('k', 'Glocke', 'glocke'),
  entry('k', 'Schrank', 'schrank'),
  entry('k', 'Stock', 'stock'),
  entry('k', 'Speck', 'speck'),
  entry('k', 'Blick', 'blick'),
  entry('k', 'Dreck', 'dreck'),
  entry('k', 'Park', 'park'),
  entry('k', 'Markt', 'markt'),
  entry('k', 'Bank', 'bank'),
  entry('k', 'Tank', 'tank'),
  entry('k', 'Kork', 'kork'),
  entry('l', 'Lampe', 'lampe'),
  entry('l', 'Laterne', 'laterne'),
  entry('l', 'Löffel', 'loeffel'),
  entry('l', 'Löwe', 'loewe'),
  entry('l', 'Lehrer', 'lehrer'),
  entry('l', 'Licht', 'licht'),
  entry('l', 'Lied', 'lied'),
  entry('l', 'Ball', 'ball'),
  entry('l', 'Apfel', 'apfel'),
  entry('l', 'Salat', 'salat'),
  entry('l', 'Tafel', 'tafel'),
  entry('l', 'Vogel', 'vogel'),
  entry('l', 'Igel', 'igel'),
  entry('l', 'Nagel', 'nagel'),
  entry('l', 'Kugel', 'kugel'),
  entry('l', 'Schule', 'schule'),
  entry('l', 'Milch', 'milch'),
  entry('l', 'Adler', 'adler'),
  entry('l', 'Blume', 'blume'),
  entry('l', 'Flasche', 'flasche'),
  entry('l', 'Glas', 'glas'),
  entry('l', 'Teller', 'teller'),
  entry('l', 'Apfelbaum', 'apfelbaum'),
  entry('l', 'Wolke', 'wolke'),
  entry('l', 'Fels', 'fels'),
  entry('l', 'Hals', 'hals'),
  entry('l', 'Wald', 'wald'),
  entry('l', 'Feld', 'feld'),
  entry('l', 'Geld', 'geld'),
  entry('l', 'Bild', 'bild'),
  entry('m', 'Mama', 'mama'),
  entry('m', 'Mond', 'mond'),
  entry('m', 'Maus', 'maus'),
  entry('m', 'Milch', 'milch'),
  entry('m', 'Mantel', 'mantel'),
  entry('m', 'Messer', 'messer'),
  entry('m', 'Meer', 'meer'),
  entry('m', 'Baum', 'baum'),
  entry('m', 'Blume', 'blume'),
  entry('m', 'Kamera', 'kamera'),
  entry('m', 'Lama', 'lama'),
  entry('m', 'Ameise', 'ameise'),
  entry('m', 'Himmel', 'himmel'),
  entry('m', 'Hammer', 'hammer'),
  entry('m', 'Tomate', 'tomate'),
  entry('m', 'Schirm', 'schirm'),
  entry('m', 'Turm', 'turm'),
  entry('m', 'Wurm', 'wurm'),
  entry('m', 'Sturm', 'sturm'),
  entry('m', 'Schaum', 'schaum'),
  entry('m', 'Daumen', 'daumen'),
  entry('m', 'Blumen', 'blumen'),
  entry('m', 'Museum', 'museum'),
  entry('m', 'Mango', 'mango'),
  entry('m', 'Melone', 'melone'),
  entry('m', 'Motorrad', 'motorrad'),
  entry('m', 'Musik', 'musik'),
  entry('m', 'Kompass', 'kompass'),
  entry('m', 'Trommel', 'trommel'),
  entry('m', 'Himbeere', 'himbeere'),
  entry('n', 'Nase', 'nase'),
  entry('n', 'Nadel', 'nadel'),
  entry('n', 'Nuss', 'nuss'),
  entry('n', 'Nest', 'nest'),
  entry('n', 'Mond', 'mond'),
  entry('n', 'Hund', 'hund'),
  entry('n', 'Kind', 'kind'),
  entry('n', 'Hand', 'hand'),
  entry('n', 'Sand', 'sand'),
  entry('n', 'Mund', 'mund'),
  entry('n', 'Banane', 'banane'),
  entry('n', 'Ananas', 'ananas'),
  entry('n', 'Garten', 'garten'),
  entry('n', 'Laterne', 'laterne'),
  entry('n', 'Engel', 'engel'),
  entry('n', 'Fenster', 'fenster'),
  entry('n', 'Sterne', 'sterne'),
  entry('n', 'Bahn', 'bahn'),
  entry('n', 'Linie', 'linie'),
  entry('n', 'Pinie', 'pinie'),
  entry('n', 'Sonne', 'sonne'),
  entry('n', 'Wanne', 'wanne'),
  entry('n', 'Kanne', 'kanne'),
  entry('n', 'Tanne', 'tanne'),
  entry('n', 'Mann', 'mann'),
  entry('n', 'Bann', 'bann'),
  entry('n', 'Zahn', 'zahn'),
  entry('n', 'Bohne', 'bohne'),
  entry('n', 'Biene', 'biene'),
  entry('n', 'Insel', 'insel'),
  entry('o', 'Ofen', 'ofen'),
  entry('o', 'Ohr', 'ohr'),
  entry('o', 'Ort', 'ort'),
  entry('o', 'Obst', 'obst'),
  entry('o', 'Orange', 'orange'),
  entry('o', 'Auto', 'auto'),
  entry('o', 'Mond', 'mond'),
  entry('o', 'Boot', 'boot'),
  entry('o', 'Vogel', 'vogel'),
  entry('o', 'Brot', 'brot'),
  entry('o', 'Dose', 'dose'),
  entry('o', 'Rose', 'rose'),
  entry('o', 'Hose', 'hose'),
  entry('o', 'Tor', 'tor'),
  entry('o', 'Torwart', 'torwart'),
  entry('o', 'Motor', 'motor'),
  entry('o', 'Radio', 'radio'),
  entry('o', 'Foto', 'foto'),
  entry('o', 'Kino', 'kino'),
  entry('o', 'Solo', 'solo'),
  entry('o', 'Polo', 'polo'),
  entry('o', 'Kokos', 'kokos'),
  entry('o', 'Mango', 'mango'),
  entry('o', 'Tomate', 'tomate'),
  entry('o', 'Konto', 'konto'),
  entry('o', 'Doktor', 'doktor'),
  entry('o', 'Pilot', 'pilot'),
  entry('o', 'Robot', 'robot'),
  entry('o', 'Sofa', 'sofa'),
  entry('o', 'Bogen', 'bogen'),
  entry('p', 'Papa', 'papa'),
  entry('p', 'Panda', 'panda'),
  entry('p', 'Pasta', 'pasta'),
  entry('p', 'Paket', 'paket'),
  entry('p', 'Pilz', 'pilz'),
  entry('p', 'Pferd', 'pferd'),
  entry('p', 'Pinsel', 'pinsel'),
  entry('p', 'Pizza', 'pizza'),
  entry('p', 'Apfel', 'apfel'),
  entry('p', 'Lampe', 'lampe'),
  entry('p', 'Teppich', 'teppich'),
  entry('p', 'Spiegel', 'spiegel'),
  entry('p', 'Apfelbaum', 'apfelbaum'),
  entry('p', 'Puppe', 'puppe'),
  entry('p', 'Park', 'park'),
  entry('p', 'Pilot', 'pilot'),
  entry('p', 'Polo', 'polo'),
  entry('p', 'Computer', 'computer'),
  entry('p', 'Clip', 'clip'),
  entry('p', 'Chip', 'chip'),
  entry('p', 'Pfeffer', 'pfeffer'),
  entry('p', 'Trompete', 'trompete'),
  entry('p', 'Ampel', 'ampel'),
  entry('p', 'Mappe', 'mappe'),
  entry('p', 'Kappe', 'kappe'),
  entry('p', 'Lippe', 'lippe'),
  entry('p', 'Raupe', 'raupe'),
  entry('p', 'Paprika', 'paprika'),
  entry('p', 'Pinselbox', 'pinselbox'),
  entry('p', 'Papagei', 'papagei'),
  entry('q', 'Qualle', 'qualle'),
  entry('q', 'Quark', 'quark'),
  entry('q', 'Quelle', 'quelle'),
  entry('q', 'Quiz', 'quiz'),
  entry('q', 'Quadro', 'quadro'),
  entry('q', 'Quarz', 'quarz'),
  entry('q', 'Quiche', 'quiche'),
  entry('q', 'Quilt', 'quilt'),
  entry('q', 'Quote', 'quote'),
  entry('q', 'Quentin', 'quentin'),
  entry('q', 'Quassel', 'quassel'),
  entry('q', 'Quader', 'quader'),
  entry('q', 'Quaste', 'quaste'),
  entry('q', 'Quirl', 'quirl'),
  entry('q', 'Quittung', 'quittung'),
  entry('q', 'Quadrat', 'quadrat'),
  entry('q', 'Quorum', 'quorum'),
  entry('q', 'Querschnitt', 'querschnitt'),
  entry('q', 'Querflöte', 'querfloete'),
  entry('q', 'Quetsche', 'quetsche'),
  entry('q', 'Quokka', 'quokka'),
  entry('q', 'Quinoa', 'quinoa'),
  entry('q', 'Quaderstein', 'quaderstein'),
  entry('q', 'Qualm', 'qualm'),
  entry('q', 'Quastenflosser', 'quastenflosser'),
  entry('q', 'Quickstep', 'quickstep'),
  entry('q', 'Quaderbau', 'quaderbau'),
  entry('q', 'Quellwasser', 'quellwasser'),
  entry('q', 'Quetschie', 'quetschie'),
  entry('q', 'Quatsch', 'quatsch'),
  entry('r', 'Rad', 'rad'),
  entry('r', 'Rose', 'rose'),
  entry('r', 'Regen', 'regen'),
  entry('r', 'Radio', 'radio'),
  entry('r', 'Rakete', 'rakete'),
  entry('r', 'Rohr', 'rohr'),
  entry('r', 'Rock', 'rock'),
  entry('r', 'Berg', 'berg'),
  entry('r', 'Dorf', 'dorf'),
  entry('r', 'Garten', 'garten'),
  entry('r', 'Lehrer', 'lehrer'),
  entry('r', 'Adler', 'adler'),
  entry('r', 'Tiger', 'tiger'),
  entry('r', 'Stern', 'stern'),
  entry('r', 'Fenster', 'fenster'),
  entry('r', 'Brief', 'brief'),
  entry('r', 'Brille', 'brille'),
  entry('r', 'Brett', 'brett'),
  entry('r', 'Turm', 'turm'),
  entry('r', 'Wurm', 'wurm'),
  entry('r', 'Sturm', 'sturm'),
  entry('r', 'Kirche', 'kirche'),
  entry('r', 'Park', 'park'),
  entry('r', 'Markt', 'markt'),
  entry('r', 'Krokodil', 'krokodil'),
  entry('r', 'Trommel', 'trommel'),
  entry('r', 'Trompete', 'trompete'),
  entry('r', 'Radar', 'radar'),
  entry('r', 'Arena', 'arena'),
  entry('r', 'Birne', 'birne'),
  entry('s', 'Sonne', 'sonne'),
  entry('s', 'Salat', 'salat'),
  entry('s', 'Sand', 'sand'),
  entry('s', 'See', 'see'),
  entry('s', 'Schiff', 'schiff'),
  entry('s', 'Schaf', 'schaf'),
  entry('s', 'Schuh', 'schuh'),
  entry('s', 'Stern', 'stern'),
  entry('s', 'Nase', 'nase'),
  entry('s', 'Hase', 'hase'),
  entry('s', 'Rose', 'rose'),
  entry('s', 'Hose', 'hose'),
  entry('s', 'Dose', 'dose'),
  entry('s', 'Tasse', 'tasse'),
  entry('s', 'Messer', 'messer'),
  entry('s', 'Glas', 'glas'),
  entry('s', 'Eis', 'eis'),
  entry('s', 'Haus', 'haus'),
  entry('s', 'Maus', 'maus'),
  entry('s', 'Bus', 'bus'),
  entry('s', 'Fest', 'fest'),
  entry('s', 'Nest', 'nest'),
  entry('s', 'Ast', 'ast'),
  entry('s', 'Kasten', 'kasten'),
  entry('s', 'Kissen', 'kissen'),
  entry('s', 'Pinsel', 'pinsel'),
  entry('s', 'Besen', 'besen'),
  entry('s', 'Wesen', 'wesen'),
  entry('s', 'Rasen', 'rasen'),
  entry('s', 'Keks', 'keks'),
  entry('t', 'Tasse', 'tasse'),
  entry('t', 'Tisch', 'tisch'),
  entry('t', 'Tiger', 'tiger'),
  entry('t', 'Tomate', 'tomate'),
  entry('t', 'Tasche', 'tasche'),
  entry('t', 'Teller', 'teller'),
  entry('t', 'Turm', 'turm'),
  entry('t', 'Auto', 'auto'),
  entry('t', 'Katze', 'katze'),
  entry('t', 'Garten', 'garten'),
  entry('t', 'Laterne', 'laterne'),
  entry('t', 'Ente', 'ente'),
  entry('t', 'Hut', 'hut'),
  entry('t', 'Brot', 'brot'),
  entry('t', 'Brett', 'brett'),
  entry('t', 'Stern', 'stern'),
  entry('t', 'Fenster', 'fenster'),
  entry('t', 'Mutter', 'mutter'),
  entry('t', 'Vater', 'vater'),
  entry('t', 'Butter', 'butter'),
  entry('t', 'Karten', 'karten'),
  entry('t', 'Wurst', 'wurst'),
  entry('t', 'Arzt', 'arzt'),
  entry('t', 'Taxi', 'taxi'),
  entry('t', 'Pasta', 'pasta'),
  entry('t', 'Pilot', 'pilot'),
  entry('t', 'Robot', 'robot'),
  entry('t', 'Motorrad', 'motorrad'),
  entry('t', 'Trommel', 'trommel'),
  entry('t', 'Trompete', 'trompete'),
  entry('u', 'Uhr', 'uhr'),
  entry('u', 'Uhu', 'uhu'),
  entry('u', 'Ufer', 'ufer'),
  entry('u', 'Unfall', 'unfall'),
  entry('u', 'Hund', 'hund'),
  entry('u', 'Mund', 'mund'),
  entry('u', 'Butter', 'butter'),
  entry('u', 'Mutter', 'mutter'),
  entry('u', 'Fuchs', 'fuchs'),
  entry('u', 'Buch', 'buch'),
  entry('u', 'Schuh', 'schuh'),
  entry('u', 'Bus', 'bus'),
  entry('u', 'Zug', 'zug'),
  entry('u', 'Flug', 'flug'),
  entry('u', 'Kuh', 'kuh'),
  entry('u', 'Hut', 'hut'),
  entry('u', 'Turm', 'turm'),
  entry('u', 'Wurm', 'wurm'),
  entry('u', 'Sturm', 'sturm'),
  entry('u', 'Blume', 'blume'),
  entry('u', 'Kugel', 'kugel'),
  entry('u', 'Schule', 'schule'),
  entry('u', 'Museum', 'museum'),
  entry('u', 'Musik', 'musik'),
  entry('u', 'Puppe', 'puppe'),
  entry('u', 'Raupe', 'raupe'),
  entry('u', 'Summe', 'summe'),
  entry('u', 'Butterdose', 'butterdose'),
  entry('u', 'Gurke', 'gurke'),
  entry('u', 'Nuss', 'nuss'),
  entry('v', 'Vogel', 'vogel'),
  entry('v', 'Vater', 'vater'),
  entry('v', 'Vase', 'vase'),
  entry('v', 'Vogelhaus', 'vogelhaus'),
  entry('v', 'Lavendel', 'lavendel'),
  entry('v', 'Klavier', 'klavier'),
  entry('v', 'Olive', 'olive'),
  entry('v', 'Oval', 'oval'),
  entry('v', 'Lava', 'lava'),
  entry('v', 'Nova', 'nova'),
  entry('v', 'Virus', 'virus'),
  entry('v', 'Video', 'video'),
  entry('v', 'Violine', 'violine'),
  entry('v', 'Vulkan', 'vulkan'),
  entry('v', 'Vanille', 'vanille'),
  entry('v', 'Ventil', 'ventil'),
  entry('v', 'Verb', 'verb'),
  entry('v', 'Vers', 'vers'),
  entry('v', 'Viertel', 'viertel'),
  entry('v', 'Vogelbeere', 'vogelbeere'),
  entry('v', 'Vollmond', 'vollmond'),
  entry('v', 'Vorbild', 'vorbild'),
  entry('v', 'Vorhang', 'vorhang'),
  entry('v', 'Vorrat', 'vorrat'),
  entry('v', 'Vulkanberg', 'vulkanberg'),
  entry('v', 'Navigator', 'navigator'),
  entry('v', 'Avocado', 'avocado'),
  entry('v', 'Lavabo', 'lavabo'),
  entry('v', 'Pullover', 'pullover'),
  entry('v', 'Revolver', 'revolver'),
  entry('w', 'Wasser', 'wasser'),
  entry('w', 'Wolf', 'wolf'),
  entry('w', 'Wald', 'wald'),
  entry('w', 'Wind', 'wind'),
  entry('w', 'Wolke', 'wolke'),
  entry('w', 'Wurst', 'wurst'),
  entry('w', 'Wurm', 'wurm'),
  entry('w', 'Schwan', 'schwan'),
  entry('w', 'Schwalbe', 'schwalbe'),
  entry('w', 'Schwein', 'schwein'),
  entry('w', 'Schwert', 'schwert'),
  entry('w', 'Zwerg', 'zwerg'),
  entry('w', 'Zwei', 'zwei'),
  entry('w', 'Waffe', 'waffe'),
  entry('w', 'Wanne', 'wanne'),
  entry('w', 'Watte', 'watte'),
  entry('w', 'Wagen', 'wagen'),
  entry('w', 'Weg', 'weg'),
  entry('w', 'Werk', 'werk'),
  entry('w', 'Wort', 'wort'),
  entry('w', 'Welt', 'welt'),
  entry('w', 'Woche', 'woche'),
  entry('w', 'Schweizer', 'schweizer'),
  entry('w', 'Schwerkraft', 'schwerkraft'),
  entry('w', 'Wunder', 'wunder'),
  entry('w', 'Winkel', 'winkel'),
  entry('w', 'Wirbel', 'wirbel'),
  entry('w', 'Wolken', 'wolken'),
  entry('w', 'Schwalbehorst', 'schwalbehorst'),
  entry('w', 'Wasserfall', 'wasserfall'),
  entry('x', 'Taxi', 'taxi'),
  entry('x', 'Hexe', 'hexe'),
  entry('x', 'Boxer', 'boxer'),
  entry('x', 'Text', 'text'),
  entry('x', 'Max', 'max'),
  entry('x', 'Fax', 'fax'),
  entry('x', 'Mixer', 'mixer'),
  entry('x', 'Xylophon', 'xylophon'),
  entry('x', 'Reflex', 'reflex'),
  entry('x', 'Index', 'index'),
  entry('x', 'Examen', 'examen'),
  entry('x', 'Extra', 'extra'),
  entry('x', 'Export', 'export'),
  entry('x', 'Express', 'express'),
  entry('x', 'Flex', 'flex'),
  entry('x', 'Fox', 'fox'),
  entry('x', 'Galaxy', 'galaxy'),
  entry('x', 'Latex', 'latex'),
  entry('x', 'Matrix', 'matrix'),
  entry('x', 'Pixel', 'pixel'),
  entry('x', 'Proxy', 'proxy'),
  entry('x', 'Saxophon', 'saxophon'),
  entry('x', 'Sphinx', 'sphinx'),
  entry('x', 'Vortex', 'vortex'),
  entry('x', 'Box', 'box'),
  entry('x', 'Axt', 'axt'),
  entry('x', 'Lux', 'lux'),
  entry('x', 'Nixe', 'nixe'),
  entry('x', 'Exot', 'exot'),
  entry('x', 'Exil', 'exil'),
  entry('y', 'Yoga', 'yoga'),
  entry('y', 'Yeti', 'yeti'),
  entry('y', 'Yacht', 'yacht'),
  entry('y', 'Yoyo', 'yoyo'),
  entry('y', 'Baby', 'baby'),
  entry('y', 'Hobby', 'hobby'),
  entry('y', 'Teddy', 'teddy'),
  entry('y', 'Party', 'party'),
  entry('y', 'Handy', 'handy'),
  entry('y', 'Story', 'story'),
  entry('y', 'Style', 'style'),
  entry('y', 'Yak', 'yak'),
  entry('y', 'Ysop', 'ysop'),
  entry('y', 'Yucca', 'yucca'),
  entry('y', 'Yoghurt', 'yoghurt'),
  entry('y', 'Yachthafen', 'yachthafen'),
  entry('y', 'Yoyospiel', 'yoyospiel'),
  entry('y', 'Babybär', 'babybaer'),
  entry('y', 'Hobbyraum', 'hobbyraum'),
  entry('y', 'Teddybär', 'teddybaer'),
  entry('y', 'Partyhut', 'partyhut'),
  entry('y', 'Handyhülle', 'handyhuelle'),
  entry('y', 'Storybook', 'storybook'),
  entry('y', 'Stylebuch', 'stylebuch'),
  entry('y', 'Yakmilch', 'yakmilch'),
  entry('y', 'Ysoptee', 'ysoptee'),
  entry('y', 'Yuccapalme', 'yuccapalme'),
  entry('y', 'Yetihelm', 'yetihelm'),
  entry('y', 'Yogamatte', 'yogamatte'),
  entry('y', 'Yogakurs', 'yogakurs'),
  entry('z', 'Zebra', 'zebra'),
  entry('z', 'Zug', 'zug'),
  entry('z', 'Zahn', 'zahn'),
  entry('z', 'Zaun', 'zaun'),
  entry('z', 'Ziege', 'ziege'),
  entry('z', 'Zucker', 'zucker'),
  entry('z', 'Zange', 'zange'),
  entry('z', 'Herz', 'herz'),
  entry('z', 'Katze', 'katze'),
  entry('z', 'Pilz', 'pilz'),
  entry('z', 'Salz', 'salz'),
  entry('z', 'Holz', 'holz'),
  entry('z', 'Netz', 'netz'),
  entry('z', 'Sitz', 'sitz'),
  entry('z', 'Blitz', 'blitz'),
  entry('z', 'Schwanz', 'schwanz'),
  entry('z', 'Schweiz', 'schweiz'),
  entry('z', 'Zwei', 'zwei'),
  entry('z', 'Zwerg', 'zwerg'),
  entry('z', 'Wurzel', 'wurzel'),
  entry('z', 'Tanz', 'tanz'),
  entry('z', 'Kurz', 'kurz'),
  entry('z', 'Satz', 'satz'),
  entry('z', 'Platz', 'platz'),
  entry('z', 'Spatz', 'spatz'),
  entry('z', 'Scherz', 'scherz'),
  entry('z', 'Pelz', 'pelz'),
  entry('z', 'Walz', 'walz'),
  entry('z', 'Malz', 'malz'),
  entry('z', 'Filz', 'filz'),
];

export function letterPickItemsForKey(key: string): LetterPickEntry[] {
  const k = key.normalize("NFC").toLocaleLowerCase("de-DE");
  return LETTER_PICK_ITEMS.filter((it) => it.key === k);
}

export function isLetterPickPuzzle(puzzle: Puzzle): boolean {
  return puzzle.type === "letterPick";
}

function indexFromRng(rng: () => number, length: number): number {
  if (length <= 0) return 0;
  const r = rng();
  const n = Number.isFinite(r) ? r : 0;
  const u = Math.min(1, Math.max(0, n));
  return Math.min(length - 1, Math.floor(u * length));
}

function shuffleInPlace<T>(arr: T[], rng: () => number): void {
  for (let i = arr.length - 1; i > 0; i -= 1) {
    const j = indexFromRng(rng, i + 1);
    const tmp = arr[i]!;
    arr[i] = arr[j]!;
    arr[j] = tmp;
  }
}

let lastHitId = "";

export function resetLetterPickPick(): void {
  lastHitId = "";
}

export function letterPickHitId(entry: LetterPickEntry): string {
  return `${entry.key}|${entry.slug}`;
}

function pickHit(rng: () => number, avoidId: string): LetterPickEntry {
  const pool = avoidId
    ? LETTER_PICK_ITEMS.filter((it) => letterPickHitId(it) !== avoidId)
    : LETTER_PICK_ITEMS;
  const list = pool.length > 0 ? pool : LETTER_PICK_ITEMS;
  const picked = list[indexFromRng(rng, list.length)]!;
  lastHitId = letterPickHitId(picked);
  return picked;
}

/** Deterministic pick by absolute index into LETTER_PICK_ITEMS. */
export function rngForLetterPickIndex(index: number): () => number {
  const len = LETTER_PICK_ITEMS.length;
  const i = ((index % len) + len) % len;
  return () => (i + 0.5) / len;
}

function pickDistractors(
  key: string,
  hitId: string,
  count: number,
  rng: () => number,
): LetterPickEntry[] {
  const candidates = LETTER_PICK_ITEMS.filter(
    (it) => letterPickHitId(it) !== hitId && !wordContainsLetter(it.display, key),
  );
  // unique by display to avoid duplicate tiles
  const byDisplay = new Map<string, LetterPickEntry>();
  for (const it of candidates) {
    if (!byDisplay.has(it.display)) byDisplay.set(it.display, it);
  }
  const unique = [...byDisplay.values()];
  shuffleInPlace(unique, rng);
  if (unique.length < count) {
    throw new Error(`letterPick: need ${count} distractors without '${key}', got ${unique.length}`);
  }
  return unique.slice(0, count);
}

/** Fill letter, five options, and solution id from catalog. */
export function realizeLetterPickPuzzle(
  puzzle: Puzzle,
  rng: () => number = Math.random,
): Puzzle {
  if (!isLetterPickPuzzle(puzzle)) return puzzle;
  const hit = pickHit(rng, lastHitId);
  const distractors = pickDistractors(hit.key, letterPickHitId(hit), 4, rng);
  const options: LetterPickOption[] = [
    {
      id: letterPickHitId(hit),
      display: hit.display,
      artPath: hit.artPath,
      voiceText: hit.display,
    },
    ...distractors.map((d) => ({
      id: letterPickHitId(d),
      display: d.display,
      artPath: d.artPath,
      voiceText: d.display,
    })),
  ];
  shuffleInPlace(options, rng);
  const upper = hit.key.toLocaleUpperCase("de-DE");
  return {
    ...puzzle,
    solution: letterPickHitId(hit),
    voiceText: "",
    prompt: `Welches Wort hat ein ${upper}?`,
    letterPickLetter: hit.key,
    letterPickOptions: options,
    anlautVisible: false,
  };
}
